#spring.application.name=UberBookingService
#
#spring.datasource.url=jdbc:mysql://localhost:3306/Uber_Db_Local
#
#spring.datasource.username=root
#
#spring.datasource.password=Sahil_201_
#
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=update
#
#server.port=7475

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: sample-group-2
      auto-offset-reset: earliest
  application:
    name: UberBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: Sahil_201_

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

