#spring.application.name=UberBookingService
#
#spring.datasource.url=jdbc:mysql://localhost:3306/Uber_Db_Local
#
#spring.datasource.username=root
#
#spring.datasource.password=Sahil_201_
#
#spring.jpa.show-sql=true
#
#spring.jpa.hibernate.ddl-auto=update
#
#server.port=7475

spring:
  application:
    name: UberBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: root
    password: Sahil_201_

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

